# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MotionSensor_POC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftOSC'
  # Pods for MotionSensor_POC

end
